name: publish
on:
  pull_request:
    branches: [ release ]

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
      
    - name: Install
      run: npm install
      
    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
